/* Generated by build.mjs from the exact Round 4 pre-projection bundle. */
window.OBSERVATORY_DATA = {
  "meta": {
    "title": "The Transition Observatory",
    "round": "Round 04",
    "classification": "research-draft",
    "asOf": "2026-09-09T00:00:00Z",
    "sourceBundleId": "bundle.round-04.worker-option.pre-projection",
    "bundleStage": "pre-projection-core",
    "evaluationClock": {
      "evaluated_at": "2026-09-09T00:00:00Z",
      "source": "operator-supplied",
      "trusted": false
    },
    "bundleCoherent": true
  },
  "condition": {
    "id": "condition.worker-option.nsw",
    "definition": {
      "condition_id": "condition.worker-option.nsw",
      "definition_version": "1.0.0",
      "definition_hash": "sha256:5ca7f32a0053e470dfb6e5eccb3f4d3d3a25718b1fbba34a0afee70ceee7272e"
    },
    "proposition": "Affected workers have a credible alternative and an accessible human review route.",
    "renderedIf": "Affected workers in the registered scope retain a credible alternative and an accessible human review route, at the standard that both registered protection predicates are satisfied, from 2026-01-01T00:00:00Z through 2026-12-31T23:59:59Z",
    "grammar": {
      "who": "Affected workers in the registered scope",
      "verb": "retain",
      "outcome": "a credible alternative and an accessible human review route",
      "standard": "both registered protection predicates are satisfied",
      "place": "New South Wales, Australia",
      "period": "2026-01-01T00:00:00Z to 2026-12-31T23:59:59Z",
      "if": "Affected workers in the registered scope retain a credible alternative and an accessible human review route, at the standard that both registered protection predicates are satisfied, from 2026-01-01T00:00:00Z through 2026-12-31T23:59:59Z"
    },
    "scope": {
      "jurisdictions": [
        "Australia"
      ],
      "geographies": [
        "New South Wales"
      ],
      "cohorts": [
        "General Clerks",
        "Payroll Clerks"
      ],
      "services": [
        "Work transition support"
      ]
    },
    "currentState": "true",
    "mechanicallyValid": true,
    "empiricalTruthEstablished": false,
    "evaluationHash": "sha256:65de9f3a480f44db48d90bb50fb89821aebe11b5192501a5e23f41dd21ade732",
    "evaluatedAt": "2026-09-09T00:00:00Z",
    "evaluationSource": "recomputed-from-executable-if-kernel",
    "observationCount": 4,
    "assessmentStatus": "open"
  },
  "states": [
    {
      "id": "true",
      "current": true,
      "action": "human-decision-required",
      "recovery": "human-review",
      "targetNodeId": "node.worker-option.protected-outcome",
      "explanation": "The registered rule matches its synthetic evidence. A human must still assess empirical truth, values, consent and authority."
    },
    {
      "id": "false",
      "current": false,
      "action": "block-edge-traversal",
      "recovery": "repair-or-alternate",
      "targetNodeId": "node.worker-option.blocked",
      "explanation": "The registered predicates do not hold. Stop this route and examine alternatives or repair the failed protection."
    },
    {
      "id": "unknown",
      "current": false,
      "action": "block-edge-traversal",
      "recovery": "acquire-missing-evidence",
      "targetNodeId": "node.worker-option.blocked",
      "explanation": "Eligible evidence is insufficient. Stop this route and collect the missing observations without presuming safety."
    },
    {
      "id": "stale",
      "current": false,
      "action": "block-edge-traversal",
      "recovery": "refresh-and-re-evaluate",
      "targetNodeId": "node.worker-option.blocked",
      "explanation": "Eligible evidence is too old. Stop this route, reacquire evidence and evaluate again."
    },
    {
      "id": "conflicted",
      "current": false,
      "action": "block-edge-traversal",
      "recovery": "adjudicate-conflict",
      "targetNodeId": "node.worker-option.blocked",
      "explanation": "Eligible evidence conflicts. Stop this route and adjudicate the disagreement without averaging it away."
    }
  ],
  "forecast": {
    "id": "forecast.worker-option.nsw.synthetic.2026.v1",
    "title": "Synthetic forecast of future credible-option coverage",
    "question": "Will the registered credible-option coverage measure meet or exceed 0.90 during the exact future observation window for the bound worker scope?",
    "probability": 0.62,
    "baselineProbability": 0.55,
    "naiveBaselineProbability": 0.5,
    "issuedAt": "2026-09-09T00:00:00Z",
    "resolveAfter": "2027-01-08T00:00:00Z",
    "resolveBy": "2027-01-31T00:00:00Z",
    "observationWindow": {
      "startsAt": "2026-09-10T00:00:00Z",
      "endsAt": "2026-12-31T23:59:59Z"
    },
    "relationToCurrentState": "orthogonal-to-current-computed-if-state",
    "claimCeiling": "This research-only forecast assigns 62% to this future event: The registered credible-option coverage measure is at or above 0.90 for the exact scope and future observation window. At issue time, 2026-09-09T00:00:00Z, the executable IF rule computed true. The probability and IF state answer different questions. Neither establishes empirical truth, causality, authority or permission to act.",
    "method": {
      "kind": "human",
      "description": "Synthetic judgement for contract testing. It is not derived from the current IF state and is not an empirical estimate.",
      "version": "fixture-1"
    },
    "status": "issued",
    "epistemicClass": "forecast",
    "use": "research_only",
    "assumptions": [
      "The probability is a synthetic judgement chosen to test the contract, not an estimate derived from validated data.",
      "The future resolution source and observation are fictional and have not been acquired.",
      "The issue-time IF receipt and forecast probability answer different questions."
    ],
    "counterHypotheses": [
      "Future credible-option coverage falls below the registered threshold.",
      "The metric or source changes materially and the forecast is voided rather than reinterpreted.",
      "The current favourable IF state fails to persist through the future observation window."
    ],
    "target": {
      "event": "The registered credible-option coverage measure is at or above 0.90 for the exact scope and future observation window.",
      "unit": "binary threshold event",
      "scope": {
        "geographies": [
          "New South Wales"
        ],
        "cohorts": [
          "General Clerks",
          "Payroll Clerks"
        ],
        "services": [
          "Work transition support"
        ]
      },
      "signal_id": "signal.option.coverage",
      "metric_id": "metric.option.coverage",
      "metric_checksum": "sha256:856a1b887e8bee10a8bdf82e5a9aa61fa2467caf61c1f59aa8a0f5413df8d902",
      "condition_id": "condition.worker-option.nsw",
      "scope_hash": "sha256:60e7ab45c3978698d76a8f4ae6a74512efd7d85cbc35d94cc11fb69f5d121868",
      "resolution_rule": "Resolve 1 only if retained resolution bytes report the registered metric at or above 0.90 for the exact signal, metric checksum, condition, scope and window. Resolve 0 if they report below 0.90. Void only under the predeclared evidence-backed policy.",
      "resolution_source": "https://example.invalid/mind-flow/round-04/employer-worker-panel.synthetic.json",
      "resolution_event_id": "event.worker-option.option-coverage.2026-future-window",
      "independence_cluster_id": "cluster.worker-option.option-coverage.2026",
      "resolver": {
        "resolver_id": "mind-flow.binary-threshold-json",
        "resolver_version": "1.1.0",
        "measure": "Share of affected workers with a credible alternative",
        "observation_unit": "ratio",
        "operator": "gte",
        "threshold": 0.9
      },
      "observation_window_start": "2026-09-10T00:00:00Z",
      "observation_window_end": "2026-12-31T23:59:59Z",
      "outcome_publication_not_before": "2027-01-08T00:00:00Z"
    }
  },
  "signals": {
    "source": {
      "id": "source.synthetic-employer-worker-panel",
      "label": "Synthetic employer-worker panel",
      "bindingStatus": "not-acquired",
      "nextAcquisition": "Create a governed synthetic source artifact or acquire approved external bytes before interpreting the candidate signals."
    },
    "contracts": [
      {
        "id": "signal.human-review.available",
        "label": "Human review available",
        "role": "readiness",
        "measure": "Whether an accessible human review route exists",
        "unit": "boolean",
        "direction": "maintain",
        "bindingKind": "executable-predicate",
        "verification": "external-unverified",
        "metricChecksum": "sha256:f23b8c2b25cf35f3998dbbc2b57c69b4ca99630fd9dab6c7bbd60bdf92239071"
      },
      {
        "id": "signal.option.coverage",
        "label": "Credible option coverage",
        "role": "confirming",
        "measure": "Share of affected workers with a credible alternative",
        "unit": "ratio",
        "direction": "increase",
        "bindingKind": "executable-predicate",
        "verification": "external-unverified",
        "metricChecksum": "sha256:856a1b887e8bee10a8bdf82e5a9aa61fa2467caf61c1f59aa8a0f5413df8d902"
      },
      {
        "id": "signal.worker-option.counter.synthetic",
        "label": "Reported earnings or essential-condition deterioration",
        "role": "counter",
        "measure": "share reporting lower real earnings or worse essential conditions",
        "unit": "ratio",
        "direction": "decrease",
        "bindingKind": "supplemental-observation",
        "verification": "external-unverified",
        "metricChecksum": "sha256:e5913de7acd3b6ebd1b0c29162386737f5bb2644cfaed0f407be9d67a17086d9"
      },
      {
        "id": "signal.worker-option.information-harm.synthetic",
        "label": "Reported transition-information harm",
        "role": "information-harm",
        "measure": "share reporting reduced clarity after transition communication",
        "unit": "ratio",
        "direction": "decrease",
        "bindingKind": "supplemental-observation",
        "verification": "external-unverified",
        "metricChecksum": "sha256:4acf65e20ddc27b9105a443705ad8e7ca327afbe7222196c71842b9353934e14"
      }
    ],
    "gaps": [
      {
        "role": "leading",
        "status": "unresolved",
        "reason": "No validated precursor is registered."
      },
      {
        "role": "outcome",
        "status": "unresolved",
        "reason": "The chosen human outcome has no independently validated measure."
      },
      {
        "role": "intervention-exposure",
        "status": "unresolved",
        "reason": "The proposed rehearsal has not started and no governed exposure record exists."
      }
    ]
  },
  "evolution": {
    "definition": {
      "changeCount": 5,
      "operations": [
        "added",
        "narrowed",
        "definition-revised",
        "split",
        "merge"
      ],
      "historyStatus": "complete-source-bound",
      "definitionVersion": "1.0.0",
      "definitionHash": "sha256:5ca7f32a0053e470dfb6e5eccb3f4d3d3a25718b1fbba34a0afee70ceee7272e"
    },
    "evidence": {
      "eventCount": 11,
      "tipEventId": "evidence-event.august-review.added",
      "stateHash": "sha256:54ec8fe8edb58bc8b66a5253870a1846f1be47d508d4276b7200ce9c2fcc63fa",
      "sourceStatus": "not-acquired"
    },
    "path": {
      "branchCount": 5,
      "historyRequirement": "complete-append-only-hash-bound",
      "policy": [
        {
          "operation": "added",
          "disposition": "fail-closed",
          "reason": "added changes or may change the evidence needed to defend this candidate path.",
          "next_action": "re-register-and-review"
        },
        {
          "operation": "narrowed",
          "disposition": "fail-closed",
          "reason": "narrowed changes or may change the evidence needed to defend this candidate path.",
          "next_action": "re-register-and-review"
        },
        {
          "operation": "definition-revised",
          "disposition": "fail-closed",
          "reason": "definition-revised changes or may change the evidence needed to defend this candidate path.",
          "next_action": "re-register-and-review"
        },
        {
          "operation": "split",
          "disposition": "fail-closed",
          "reason": "split changes or may change the evidence needed to defend this candidate path.",
          "next_action": "re-register-and-review"
        },
        {
          "operation": "merge",
          "disposition": "fail-closed",
          "reason": "merge changes or may change the evidence needed to defend this candidate path.",
          "next_action": "re-register-and-review"
        },
        {
          "operation": "challenged",
          "disposition": "fail-closed",
          "reason": "challenged changes or may change the evidence needed to defend this candidate path.",
          "next_action": "re-register-and-review"
        },
        {
          "operation": "satisfied",
          "disposition": "fail-closed",
          "reason": "satisfied changes or may change the evidence needed to defend this candidate path.",
          "next_action": "re-register-and-review"
        },
        {
          "operation": "failed",
          "disposition": "fail-closed",
          "reason": "failed changes or may change the evidence needed to defend this candidate path.",
          "next_action": "re-register-and-review"
        },
        {
          "operation": "expired",
          "disposition": "fail-closed",
          "reason": "expired changes or may change the evidence needed to defend this candidate path.",
          "next_action": "re-register-and-review"
        },
        {
          "operation": "superseded",
          "disposition": "fail-closed",
          "reason": "superseded changes or may change the evidence needed to defend this candidate path.",
          "next_action": "re-register-and-review"
        },
        {
          "operation": "disputed",
          "disposition": "fail-closed",
          "reason": "disputed changes or may change the evidence needed to defend this candidate path.",
          "next_action": "re-register-and-review"
        },
        {
          "operation": "withdrawn",
          "disposition": "fail-closed",
          "reason": "withdrawn changes or may change the evidence needed to defend this candidate path.",
          "next_action": "re-register-and-review"
        }
      ]
    },
    "actorValues": {
      "goal": "Affected people gain durable agency and share in technological abundance without involuntary loss of real earnings or essential conditions.",
      "classification": "value-choice",
      "selectionAuthority": "external-unverified",
      "affectedPopulations": [
        {
          "population_id": "population.affected-workers.nsw",
          "label": "General Clerks and Payroll Clerks in the registered New South Wales scope",
          "effect_channel": "Work, real earnings, essential conditions, choice, review access and information harm",
          "voice_status": "not-consulted"
        },
        {
          "population_id": "population.dependent-households",
          "label": "Households that depend on earnings from affected workers",
          "effect_channel": "Income stability, care responsibilities and mobility burden",
          "voice_status": "not-consulted"
        }
      ],
      "omissions": {
        "status": "identified",
        "entries": [
          {
            "population_id": "population.omitted.precarious-workers",
            "label": "Workers with temporary, visa-linked, casual or otherwise precarious bargaining positions",
            "omission_reason": "The registered aggregate scope does not separately represent constraints on refusal, appeal or mobility.",
            "consequence": "A route described as voluntary for the aggregate may remain coercive for these workers.",
            "remedy": "Co-design separate refusal, continuity and review tests with affected workers and qualified advocates before use.",
            "public_notice": "Workers with precarious bargaining positions are not adequately represented by this synthetic path."
          }
        ],
        "search_method": "Synthetic enumeration across worker, household, employer, service, legal-status and communication channels.",
        "search_limitations": "No affected-party consultation or representative sampling has occurred. Further omissions are expected."
      }
    }
  },
  "paths": {
    "candidate": {
      "id": "path.round-04.worker-option.synthetic",
      "title": "A worker-controlled route through automation-related work change",
      "summary": "A reversible support rehearsal may help affected workers preserve meaningful choice while institutions learn where access, refusal, review and communication safeguards fail.",
      "status": "proposed-not-started",
      "publicClaimCeiling": "Synthetic possible path, not a finding: Affected workers inside the complete registered observation scope may navigate automation-related work change to the following standard: without involuntary loss of real earnings or essential conditions, while retaining a credible alternative and accessible human review, in New South Wales, Australia, during 2026-01-01T00:00:00Z to 2026-12-31T23:59:59Z, only if Affected workers in the registered scope retain a credible alternative and an accessible human review route, at the standard that both registered protection predicates are satisfied, from 2026-01-01T00:00:00Z through 2026-12-31T23:59:59Z. Affected populations: General Clerks and Payroll Clerks in the registered New South Wales scope; Households that depend on earnings from affected workers. Scope omissions: Workers with precarious bargaining positions are not adequately represented by this synthetic path. Named competing paths: Work is redesigned in place with protected roles; Work contracts without a protected route. This open-world hypothesis is unscored and grants no action authority."
    },
    "competitors": [
      {
        "path_id": "path.competitor.in-place-redesign",
        "label": "Work is redesigned in place with protected roles",
        "selection_reason": "It could preserve the chosen outcome without occupational transition support as the main mechanism.",
        "incompatible_claim": "Most adaptation occurs inside retained roles rather than through the candidate support route.",
        "discriminating_observations": [
          {
            "observation_id": "observation.role-retention-mechanism",
            "construct": "Worker-level role retention, task redesign and use of transition support",
            "possible_path_pattern": "Affected workers voluntarily use a credible option and accessible review route.",
            "competing_path_pattern": "Affected workers retain redesigned roles and rarely use transition support.",
            "period": "2026-01-01T00:00:00Z to 2026-12-31T23:59:59Z",
            "source_plan": "Pre-register consented worker observations and independently audited employer task records. No source is acquired here.",
            "status": "unresolved"
          }
        ]
      },
      {
        "path_id": "path.competitor.unsupported-contraction",
        "label": "Work contracts without a protected route",
        "selection_reason": "It tests whether apparent adaptation hides exits, lost earnings or constrained choice.",
        "incompatible_claim": "Affected workers leave or lose work without the registered option and review safeguards.",
        "discriminating_observations": [
          {
            "observation_id": "observation.unsupported-exit-mechanism",
            "construct": "Worker exits, real earnings, essential conditions and registered support exposure",
            "possible_path_pattern": "Affected workers retain the chosen standard with a recorded credible option and review route.",
            "competing_path_pattern": "Affected workers exit without the safeguards or do not retain the chosen standard.",
            "period": "2026-01-01T00:00:00Z to 2026-12-31T23:59:59Z",
            "source_plan": "Acquire consented longitudinal worker records with independent access and harm audits. No source is acquired here.",
            "status": "unresolved"
          }
        ]
      }
    ],
    "graph": {
      "entry_node_id": "node.worker-option.context",
      "nodes": [
        {
          "node_id": "node.worker-option.context",
          "kind": "context",
          "label": "Automation-related work change reaches the registered worker scope",
          "affected_population_ids": [
            "population.affected-workers.nsw"
          ]
        },
        {
          "node_id": "node.worker-option.protected-outcome",
          "kind": "outcome",
          "label": "Affected workers reach the chosen protection standard after human review",
          "affected_population_ids": [
            "population.affected-workers.nsw"
          ]
        },
        {
          "node_id": "node.worker-option.blocked",
          "kind": "abandonment",
          "label": "This candidate route stops while evidence, freshness or disagreement is resolved",
          "affected_population_ids": [
            "population.affected-workers.nsw"
          ]
        }
      ],
      "edges": [
        {
          "edge_id": "edge.worker-option.consider-protected-route",
          "from_node_id": "node.worker-option.context",
          "to_node_id": "node.worker-option.protected-outcome",
          "kind": "consequential-decision",
          "label": "Consider the protected route only after the exact IF receipt is reviewed",
          "condition_bindings": [
            {
              "condition_id": "condition.worker-option.nsw",
              "ledger_ref": "urn:mind-flow:evolution:ledger.round-04.worker-option.synthetic",
              "ledger_manifest_hash": "sha256:fd258eecb21ecdc57f157f3b4b7f4b9db85f548bab52398b2c1e063eb753c7c2",
              "condition_version": 1,
              "as_of_sequence": 5,
              "as_of_event_id": "event.worker-option.merge",
              "as_of_event_hash": "sha256:fa558c5398a40fae22eeabe65b6d987b15b013786b5e1c6c698b7abfe67340c6",
              "outcome_scope_hash": "sha256:6297bdb10971769c2ddb5f2edbbaf44ba733bf34d3e2e2969efd67d2a4822e3e",
              "canonical_binding_hash": "sha256:ab20df9059dc86bb7f919ba403d975107dfefca21467954d1942620c1a9fb875"
            }
          ],
          "branches": {
            "if_true": {
              "target_node_id": "node.worker-option.protected-outcome",
              "action": "human-decision-required",
              "recovery": "human-review",
              "public_explanation": "The registered rule matches its synthetic evidence. A human must still assess empirical truth, values, consent and authority."
            },
            "if_false": {
              "target_node_id": "node.worker-option.blocked",
              "action": "block-edge-traversal",
              "recovery": "repair-or-alternate",
              "public_explanation": "The registered predicates do not hold. Stop this route and examine alternatives or repair the failed protection."
            },
            "if_unknown": {
              "target_node_id": "node.worker-option.blocked",
              "action": "block-edge-traversal",
              "recovery": "acquire-missing-evidence",
              "public_explanation": "Eligible evidence is insufficient. Stop this route and collect the missing observations without presuming safety."
            },
            "if_stale": {
              "target_node_id": "node.worker-option.blocked",
              "action": "block-edge-traversal",
              "recovery": "refresh-and-re-evaluate",
              "public_explanation": "Eligible evidence is too old. Stop this route, reacquire evidence and evaluate again."
            },
            "if_conflicted": {
              "target_node_id": "node.worker-option.blocked",
              "action": "block-edge-traversal",
              "recovery": "adjudicate-conflict",
              "public_explanation": "Eligible evidence conflicts. Stop this route and adjudicate the disagreement without averaging it away."
            }
          }
        }
      ]
    },
    "crisisVerdictProduced": false,
    "nonTrueDecisionGates": [
      {
        "id": "false",
        "current": false,
        "action": "block-edge-traversal",
        "recovery": "repair-or-alternate",
        "targetNodeId": "node.worker-option.blocked",
        "explanation": "The registered predicates do not hold. Stop this route and examine alternatives or repair the failed protection."
      },
      {
        "id": "unknown",
        "current": false,
        "action": "block-edge-traversal",
        "recovery": "acquire-missing-evidence",
        "targetNodeId": "node.worker-option.blocked",
        "explanation": "Eligible evidence is insufficient. Stop this route and collect the missing observations without presuming safety."
      },
      {
        "id": "stale",
        "current": false,
        "action": "block-edge-traversal",
        "recovery": "refresh-and-re-evaluate",
        "targetNodeId": "node.worker-option.blocked",
        "explanation": "Eligible evidence is too old. Stop this route, reacquire evidence and evaluate again."
      },
      {
        "id": "conflicted",
        "current": false,
        "action": "block-edge-traversal",
        "recovery": "adjudicate-conflict",
        "targetNodeId": "node.worker-option.blocked",
        "explanation": "Eligible evidence conflicts. Stop this route and adjudicate the disagreement without averaging it away."
      }
    ],
    "abandonment": {
      "default": "stop-and-retain-history",
      "triggers": [
        {
          "trigger_id": "trigger.non-true-or-invalid-state",
          "condition": "The exact IF receipt is false, unknown, stale, conflicted or mechanically invalid.",
          "disposition": "abandon-path-and-retain-record",
          "reason": "No consequential route may inherit assurance from missing, old or disputed evidence."
        },
        {
          "trigger_id": "trigger.unrepresented-harm",
          "condition": "An affected or omitted population reports material harm that the registered scope does not cover.",
          "disposition": "abandon-path-and-retain-record",
          "reason": "Aggregate progress cannot silently trade away an under-represented population."
        }
      ],
      "public_notice": "Stopping this candidate path does not establish a competitor. It records what failed and what must be learned next."
    },
    "gamingRisks": [
      {
        "risk_id": "risk.option-relabeling",
        "mechanism": "A provider or employer could relabel constrained redeployment as a credible option.",
        "early_observation": "Audit refusal, appeal use, adverse employment events and worker comprehension before interpreting coverage.",
        "response": "Pause the path, retain records and require worker-accessible independent review.",
        "residual_unknown": "Informal coercion may remain hidden even when formal refusal is recorded."
      },
      {
        "risk_id": "risk.communication-certainty",
        "mechanism": "Publishing a favourable rule state could be mistaken for empirical truth, entitlement or permission.",
        "early_observation": "Test whether affected people can distinguish rule state, evidence quality, freshness and authority.",
        "response": "Withdraw or redesign communication when misunderstanding or pressure rises.",
        "residual_unknown": "Public interpretation may change as institutions respond to the signal."
      }
    ]
  },
  "preparation": {
    "id": "action.prepare-worker-option-support",
    "publicSentence": "Proposal: prepare a private worker-controlled option and human-review support file IF the computed IF state is false, unknown, stale, conflicted. Re-evaluate before starting. Eligibility is not authority. This record does not authorise action.",
    "actor": {
      "actor_id": "actor.affected-worker.candidate",
      "name": "A candidate affected worker",
      "identity_state": "candidate-unverified",
      "authority_boundary": "May prepare their own private support file; may not represent peers, command providers or commit public resources."
    },
    "verb": "prepare",
    "object": "a private worker-controlled option and human-review support file",
    "eligibleStates": [
      "false",
      "unknown",
      "stale",
      "conflicted"
    ],
    "blockedStates": [
      "true"
    ],
    "currentlyEligible": false,
    "reEvaluateBeforeStart": true,
    "reversibility": {
      "class": "reversible",
      "rationale": "The private draft can be paused or deleted without changing employment, services or public entitlements.",
      "residual_harm": "The rehearsal could still create anxiety, false confidence or privacy risk.",
      "default_rule": "reversible-unless-higher-gate-passed"
    },
    "resources": {
      "reporting_basis": "caller-asserted-not-authenticated",
      "funding_status": "unfunded",
      "capacity_status": "unavailable"
    },
    "controls": {
      "start_conditions": [
        {
          "gate": "if-state-eligible",
          "test": "A newly computed receipt is in an eligible state.",
          "failure_effect": "Do not start."
        },
        {
          "gate": "receipt-current",
          "test": "The receipt uses the current definition and evidence tips.",
          "failure_effect": "Recompute before considering the proposal."
        },
        {
          "gate": "resources-ready",
          "test": "The worker confirms private time and support capacity are available.",
          "failure_effect": "Do not start."
        },
        {
          "gate": "human-approval",
          "test": "The affected worker freely chooses to proceed.",
          "failure_effect": "Do not start."
        }
      ],
      "stop_conditions": [
        {
          "gate": "condition-state-changed",
          "test": "The computed IF state changes.",
          "failure_effect": "Stop and reassess the trigger."
        },
        {
          "gate": "receipt-invalidated",
          "test": "Any receipt binding or source is invalidated.",
          "failure_effect": "Stop and recompute."
        },
        {
          "gate": "safeguard-failed",
          "test": "Privacy, voluntariness or review safeguards fail.",
          "failure_effect": "Stop and protect the worker."
        }
      ],
      "review_conditions": [
        {
          "gate": "weekly-worker-review",
          "test": "The worker reviews usefulness and any information harm.",
          "failure_effect": "Revise or abandon the rehearsal."
        }
      ]
    },
    "reviewBy": "2026-09-16T00:00:00Z",
    "decisionUse": "research-only",
    "authorisationEffect": "none"
  },
  "authority": {
    "effect": "none",
    "actionAuthorised": false,
    "publicationApproved": false,
    "humanDecisionRequired": true,
    "authorityStatus": "externally-unverified",
    "nextCheck": "Name and independently verify a lawful owner with affected-party challenge before any decision-linked use."
  },
  "provenance": {
    "bundlePath": "integration/transition-bundle/fixtures/round-04.worker-option.pre-projection.json",
    "artifacts": [
      {
        "role": "agency-map",
        "path": "contracts/agency-map/fixtures/round-04.worker-option.synthetic.json",
        "sha256": "sha256:74b1901e50d79fbe4288b90be45c20b0e1bb22b264885bc5b3d60575086bd439"
      },
      {
        "role": "evolution-ledger",
        "path": "contracts/evolution/fixtures/round-04.worker-option.synthetic.json",
        "sha256": "sha256:5465cf4e2844af6af0fbc745b70b2bb884849fd04245215efc6122c139549377"
      },
      {
        "role": "signal-registry",
        "path": "signals/fixtures/round-04.worker-option.synthetic.json",
        "sha256": "sha256:448ce8cbf795c53b0d9cd492de15abf218143c1df177905e61b479e1ad7b4bbb"
      },
      {
        "role": "possible-path",
        "path": "paths/fixtures/round-04.worker-option.synthetic.json",
        "sha256": "sha256:77fdc6a075fd0331630e55009716969852dc3624f1eda553c2eb02b3022bcd8a"
      },
      {
        "role": "preparation-register",
        "path": "preparation/fixtures/valid/round-04.worker-option.synthetic.json",
        "sha256": "sha256:925f03ffae576529d005b0eb661097f8bb732fd3bc657383866f3a5ce995f6ec"
      },
      {
        "role": "forecast",
        "path": "forecasts/fixtures/round-04.worker-option.synthetic.json",
        "sha256": "sha256:0e132cdd23c6c611ce32fa0ca74de9a2f93bcce155153f5626c4d88437c156e7"
      },
      {
        "role": "executable-if-kernel",
        "path": "contracts/executable-if/fixtures/kernel.synthetic.json",
        "sha256": "sha256:89da70e67ea7acab1256a6022528b9ad086b94a4eddfd56954feb4f22870778b"
      }
    ],
    "rootRole": "agency-map",
    "kernelId": "kernel.worker-option.synthetic",
    "kernelManifestHash": "sha256:c248487bfa576fa7fd7f5aff532192f6b83e32a1743dc6fc90842d4c0d4fcf21",
    "evidenceTipEventId": "evidence-event.august-review.added",
    "evidenceStateHash": "sha256:54ec8fe8edb58bc8b66a5253870a1846f1be47d508d4276b7200ce9c2fcc63fa"
  }
};
